name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We value your ideas for making ai-coreutils better.

  - type: dropdown
    id: component
    attributes:
      label: Component Type
      description: What type of component is this feature for?
      options:
        - Slash Command
        - Agent
        - Hook
        - MCP Server
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: "I also thought about..."

  - type: textarea
    id: use-case
    attributes:
      label: Use Case Example
      description: Provide a concrete example of how you'd use this feature
      placeholder: |
        ```bash
        /new-command input
        # Expected output...
        ```
    validations:
      required: true

  - type: checkboxes
    id: unix-philosophy
    attributes:
      label: Unix Philosophy Alignment
      description: Does this feature align with Unix philosophy?
      options:
        - label: Small, focused, does one thing well
        - label: Composable with other commands/tools
        - label: Generic, not project-specific
        - label: Adds semantic value beyond simple wrappers

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request
