name: Question
description: Ask a question about ai-coreutils
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation
        - Usage
        - Development/Contributing
        - Slash Commands
        - Agents
        - Hooks
        - MCP Servers
        - Philosophy/Design
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or what you've already tried
      placeholder: I tried... but...

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Anything else we should know?
